language: python
python:
    - "3.7"
    - "3.8"
install:
    - pip install tox
script:
    - tox -r
matrix:
    include:
        -os: windows
        - python: 3.8
          env: TOXENV=style

        - python: 3.8
          env: TOXENV=coverage

        - python: 3.8
          env: TOXENV=docstyle

        - python: 3.8
          env: TOXENV=docs

        - python: 3.7
          env: TOXENV=py37

        - python: 3.8
          env: TOXENV=py38
