language: python

python:
    - 3.7
    - 3.8

install:
    - pip install tox

script:
    - tox -r

matrix:
    include:
        - os: windows
          python: 3.8
          env: TOXENV=style

        - os: windows
          python: 3.8
          env: TOXENV=coverage

        - os: windows
          python: 3.8
          env: TOXENV=docstyle

        - os: windows
          python: 3.8
          env: TOXENV=docs

        - os: windows
          python: 3.7
          env: TOXENV=py37

        - os: windows
          python: 3.8
          env: TOXENV=py38
